# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#------------------------------------------------------------------------------

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NLP with Friends
subtitle: By students, for students
email: nlp.with.friends@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  NLP with friends is an online seminar series made by students, for students, where everyone is invited.
twitter_username: username
github_username: nlp-with-friends
minimal_mistakes_skin: "mint" #default
search: true
url: https://nlp-with-friends.github.io
baseurl: "/"
repository: nlp-with-friends/nlp-with-friends.github.io
logo: "/assets/images/logo.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /past/:title/
paginate: 5 # amount of posts to show
paginate_path: /past/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-172489678-1" # Replace this with your ID, or delete
    anonymize_ip         : true

# Default Site 'Author' (next speaker)
author: 
  next   : "yes"
  home   : "/upcoming"
  name   : "Lena Voita"
  avatar : "https://lena-voita.github.io/img/people/lena-min.png"
  bio    : "Information-Theoretic Probing with Minimum Description Length"
  links:
    - label: "Aug 05, 2020"
      icon: "far fa-fw fa-calendar-alt"
      url: "/upcoming"
    - label: "14:00 UTC"
      icon: "far fa-fw fa-clock"
      url: "https://www.timeanddate.com/worldclock/converter.html?iso=20200805T140000&p1=224&p2=179&p3=136&p4=676&p5=33&p6=152"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lena-voita.github.io/"
    - label: "Register!"
      icon: "fas fa-fw fa-user-plus"
      url: "https://www.eventbrite.co.uk/e/nlp-with-friends-featured-friend-lena-voita-tickets-114590039894"

footer:
  links:
    - label: "Contact Us"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:nlp.with.friends@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/NLPwithFriends"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
